-- Bitacora NOA: ejecutar en Supabase > SQL Editor.
-- La seguridad depende de RLS: cada registro solo es visible para su propietario.

create table if not exists public.memories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  text text not null check (char_length(text) between 1 and 5000),
  place text,
  memory_date date,
  mood text not null default '✦',
  created_at timestamptz not null default now()
);

create table if not exists public.checklist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,
  completed boolean not null default false,
  position integer not null default 0,
  unique (user_id, label)
);

create table if not exists public.media (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_path text not null unique,
  file_name text not null,
  mime_type text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  resource_type text not null check (resource_type in ('memory', 'media')),
  resource_id text not null,
  unique (user_id, resource_type, resource_id)
);

alter table public.memories enable row level security;
alter table public.checklist_items enable row level security;
alter table public.media enable row level security;
alter table public.favorites enable row level security;

drop policy if exists "Users manage their memories" on public.memories;
drop policy if exists "Users manage their checklist" on public.checklist_items;
drop policy if exists "Users manage their media" on public.media;
drop policy if exists "Users manage their favorites" on public.favorites;
create policy "Users manage their memories" on public.memories for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their checklist" on public.checklist_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their media" on public.media for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their favorites" on public.favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public) values ('noa-media', 'noa-media', false)
on conflict (id) do nothing;

drop policy if exists "Users upload their media" on storage.objects;
drop policy if exists "Users read their media" on storage.objects;
drop policy if exists "Users delete their media" on storage.objects;
create policy "Users upload their media" on storage.objects for insert to authenticated
with check (bucket_id = 'noa-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Users read their media" on storage.objects for select to authenticated
using (bucket_id = 'noa-media' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "Users delete their media" on storage.objects for delete to authenticated
using (bucket_id = 'noa-media' and (storage.foldername(name))[1] = auth.uid()::text);
